version: "3.7"
# convenient compose file for Self-hosted LiveSync.
# Initial Author: @arminus
# Modified      : @vrtmrz

services:
    caddy:
        image: lucaslorentz/caddy-docker-proxy:ci-alpine
        container_name: caddy
        ports:
            - 80:80
            - 443:443
        environment:
            - CADDY_INGRESS_NETWORKS=caddy
        networks:
            - caddy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./data/caddy:/data
        restart: always

    couchserver:
        image: couchdb:3.1.2
        ports:
            - "5984:5984"
        environment:
            - COUCHDB_USER=${COUCHDB_USER}
            - COUCHDB_PASSWORD=${COUCHDB_PW}
        volumes:
            # The files' owner will be id:5984 when you launch the image.
            # Because CouchDB writes on-the-fly configurations into local.ini.
            # So when you want to perform git pull or change something, you have to change owners back.
            - ./data/couchdb:/opt/couchdb/data
            - ./conf/local.ini:/opt/couchdb/etc/local.ini
        networks:
            - caddy
        labels:
            caddy: ${COUCHDB_SERVER}
            caddy.reverse_proxy: "{{upstreams 5984}}"
            caddy.header.-Server: ""
        restart: always

networks:
  caddy:
    external: true
